### PR TITLE
Closes #6

### LINKED ISSUE #6: Unable to compile in OpenCV 4.2
Hi @sthoduka,

Thank you for providing and maintaining this reference code. It has helped me understand better how Fourier Mellin transform works and how robust it can be given noise in image evaluation. :smile: 

When attempting to compile the code using OpenCV 4.2, it generates the following error.
```bash
# Compiling the code
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```

```bash
/home/user/imreg_fmt/src/image_transforms.cpp: In member function ‘void ImageTransforms::remapLogPolar(const cv::Mat&, cv::Mat&)’:
/home/user/imreg_fmt/src/image_transforms.cpp:52:43: error: ‘CV_INTER_CUBIC’ was not declared in this scope
   52 |     cv::remap(src, dst, cv_xMap, cv_yMap, CV_INTER_CUBIC & cv::INTER_MAX, cv::BORDER_CONSTANT, cv::Scalar());

```

## Cause of Issue
This build failure is caused by the fact I am using OpenCV 4.2 and therefore [some MACROS in OpenCV 2.4 are not present in newer versions](https://answers.ros.org/question/214031/catkin_make-error-cv_inter_linear-was-not-declared-in-this-scope/?answer=371308#post-id-371308).

This issue is addressed by Pull Request #7.

### PR DESCRIPTION
**Pull request by cardboardcode**
Hi @sthoduka,

Once again, thank you for this reference code.

## Purpose of Pull Request
This pull request contains 2 edits that allow **imreg_fmt** to be compiled successfully with **OpenCV 4.2**.

1. Updated OpenCV MACROS in `image_registration.cpp` , `image_transforms.cpp` and `image_main.cpp`.
2. Updated `README.md` to reflect new dependencies.

### CODE REVIEW

**Comment by sthoduka** [comment]
hello @cardboardcode, thanks a lot! I'm glad the code has been helpful for you. I will merge this now. At some point I will try to see if it's possible to make the code compatible with both versions.
