### ISSUE TITLE
Unable to compile in OpenCV 4.2

### ISSUE THREAD

**Issue by cardboardcode** [sthoduka/imreg_fmt#6]
Hi @sthoduka,

Thank you for providing and maintaining this reference code. It has helped me understand better how Fourier Mellin transform works and how robust it can be given noise in image evaluation. :smile: 

## Issue Description
> I do note that the code is meant to compile only with OpenCV 2.4. Therefore, this issue is only created to justify a pull request I will be making shortly. 

When attempting to compile the code using OpenCV 4.2, it generates the following error.
```bash
# Compiling the code
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```

```bash
/home/user/imreg_fmt/src/image_transforms.cpp: In member function ‘void ImageTransforms::remapLogPolar(const cv::Mat&, cv::Mat&)’:
/home/user/imreg_fmt/src/image_transforms.cpp:52:43: error: ‘CV_INTER_CUBIC’ was not declared in this scope
   52 |     cv::remap(src, dst, cv_xMap, cv_yMap, CV_INTER_CUBIC & cv::INTER_MAX, cv::BORDER_CONSTANT, cv::Scalar());

```

## Cause of Issue
This build failure is caused by the fact I am using OpenCV 4.2 and therefore [some MACROS in OpenCV 2.4 are not present in newer versions](https://answers.ros.org/question/214031/catkin_make-error-cv_inter_linear-was-not-declared-in-this-scope/?answer=371308#post-id-371308).

This issue is addressed by Pull Request #7.
